services:
  ejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projeto-2-ejs
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
    expose:
      - "3000"
    networks:
      - proxy-network
      - database-network

networks:
  proxy-network:
    external: true
  database-network:
    external: true
    name: shared-db-network
